### PR TITLE
fix: correctly change node status after successful ping

### LINKED ISSUE #1387: After a successful ping, devices are not detected as awake/alive
https://github.com/zwave-js/node-zwave-js/issues/1364#issuecomment-760016477

### PR DESCRIPTION
**Pull request by AlCalzone**
fixes: #1387

### CODE REVIEW

**Comment by AlCalzone** [comment]
@zwave-js-bot pack this

File: packages/zwave-js/src/lib/driver/Driver.ts [hunk 1]
```diff
@@ -2047,6 +2044,8 @@ ${handlers.length} left`,
 					if (!node.keepAwake) {
 						this.debounceSendNodeToSleep(node);
 					}
+					// The node must be awake because it answered
+					node.markAsAwake();
```
Comment (jcam) [inline packages/zwave-js/src/lib/driver/Driver.ts:2048]: This looks odd, the previous line would be sending the node to sleep, ergo it would not be awake anymore... right? should this be markAsAlive()?

Comment (AlCalzone) [reply packages/zwave-js/src/lib/driver/Driver.ts:2048]: Not entirely correct. The previous line will actively send the node to sleep after 1 second if there are no messages for it in the queue. Until then, it is awake.

Comment (jcam) [reply packages/zwave-js/src/lib/driver/Driver.ts:2048]: right! because this is fast :)

Comment (AlCalzone) [reply packages/zwave-js/src/lib/driver/Driver.ts:2048]: And depending on the queue length, the "send to sleep" might take pretty long until it actually happens.
