### PR TITLE
fix(cc): do not query all user codes during interview

### LINKED ISSUE #2725: Yale lock code query disables device, and kills the battery due to looping NodeInfo
**Checklist:**

-   [x] My problem is **not** within Home Assistant or the ZWave JS integration. **Or:** a Home Assistant developer has told me to come here.
-   [x] My problem is **not** within ZWaveJS2MQTT. **Or:** a ZWaveJS2MQTT developer has told me to come here.
-   [x] I have checked the troubleshooting section and my problem is **not** described there.
-   [x] I have read the changelog and my problem was **not** mentioned there.

**Describe the bug**
I use ZWaveJS2MQTT but the zwave logic for this I believe comes from  ZWave JS directly hence filing here.

Yale lock node user code update / interview is strobing the device batteries to death.

I have 5 Yale Assure Touchscreen Deadbolts on my network and due to a bug in ZWaveJS2MQTT (possibly https://github.com/zwave-js/zwavejs2mqtt/issues/998) after restarting, sometimes they have to be re-interviewed to work again (but just adding them the first time was the same hassle) as they all go to "Unknown manufacturer 0xXXXX".

It seems that the NodeInfo loop gets all the relevant details from the lock, then proceeds to query all user codes, I believe there are 254 (?) or so, but it gets to 15-20 when the node doesn't respond quickly enough, and it gives up on the interview, then restarts it several times, even eventually declaring the node dead, or getting stuck in an interview loop until it depletes all the batteries. While this is going on the lock is unresponsive to commands.

This makes the locks effectively useless as I can't control them and can't even use them as "dumb" locks (keypad or auto relock) as the interview eats the 4 AA batteries in a day or two.

Could the code query be deferred so the device can finish NodeInfo without it, and then in a separate, more lenient loop fetch them without maybe restarting from the start every single time?

**Device information**

Which device(s) is/are affected (manufacturer/model)? 
They report in as: Yale | Assure Touchscreen Deadbolt | YRD226,  YRD246 and YRL256

What is/are the node IDs?
Node 24
Node 37
Node 43
Node 45
Node 50

**Did you change anything?**

-   [ ] **Yes**: _(please describe)_
-   [x] **No**

**Did this use to work before?**

-   [ ] **Don't know**, this is a new device
-   [x] **No**, it never worked anywhere
-   [ ] **Yes**, in: _(specify application with versions)_

**How are you using `node-zwave-js`**

-   [ ] `zwavejs2mqtt` (latest) docker image
-   [ ] `zwavejs2mqtt` (dev) docker image
-   [ ] `zwavejs2mqtt` Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] ioBroker.zwave2 adapter
-   [x] `HomeAssistant` version was zwavejs2mqtt 0.17.0 now 0.18.0 (zwavejs2mqtt: 4.5.0 zwave-js: 7.7.0)
-   [ ] Pkg
-   [ ] Manual Docker build
    -   `node-zwave-js` branch: 
    -   `zwavejs2mqtt` branch: 
-   [ ] `node-red-contrib-zwave-js`
    -   Module version (double click node): 
-   [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github))
-   [ ] Other: 

**To Reproduce**

Try to add a Yale lock, or re-interview one.
[zwavejs2mqtt.log](https://github.com/zwave-js/node-zwave-js/files/6563288/zwavejs2mqtt.log)

### LINKED ISSUE #2727: Do not query all user codes during interview

### PR DESCRIPTION
**Pull request by sybohy**
This PR is a proposed solution for #2727. More specifically, we expose the ability to skip the interviewing of user code by setting a `skipUserCodeInterview` flag in the ZWaveOptions being passed to the driver.

### CODE REVIEW

**Comment by sybohy** [comment]
@AlCalzone I have a couple of questions here.

First, do we want the default behavior to be NOT querying all the user codes? If so, I need to fix this because right now the default behavior is still to scan them.

Second, if we merge this as a 8.0 release and are ok with breaking changes, then I would suggest restructuring the zwave options from this:

```typescript
...
/**
* @internal
* Set this to true to skip the controller interview. Useful for testing purposes
*/
skipInterview?: boolean;

/** Allows you to skip user code interview */
skipUserCodeInterview?: boolean;
...
```


to maybe this?

```typescript
interviewBehavior: {
  skipInterview?: boolean;
  skipUserCodeInterview?: boolean;
}
```

File: packages/zwave-js/src/lib/driver/ZWaveOptions.ts [hunk 1]
```diff
@@ -59,6 +59,9 @@ export interface ZWaveOptions {
 	 */
 	skipInterview?: boolean;
 
+	/** Allows you to skip user code interview */
+	skipUserCodeInterview?: boolean;
```
Comment (sybohy) [inline packages/zwave-js/src/lib/driver/ZWaveOptions.ts]: if we want to flip the default behavior to skip by default, we can maybe rename this `doNotSkipUserCodeInterview` or `interviewUserCodes`.

Comment (AlCalzone) [reply packages/zwave-js/src/lib/driver/ZWaveOptions.ts]: I'd make **not scanning** user codes the default for 8.0.0 and call the flag to restore the previous behavior `queryAllUserCodes`.
Moving `skipInterview` there is okay, we just need to update tests that use it.

File: packages/zwave-js/src/lib/commandclass/UserCodeCC.ts [hunk 2]
```diff
@@ -756,7 +756,9 @@ export class UserCodeCC extends CommandClass {
 		}
 
 		// Synchronize user codes and settings
-		await this.refreshValues();
+		if (!this.driver.options.skipUserCodeInterview) {
```
Comment (AlCalzone) [inline packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]: When we end up not querying the codes, we still need to create default metadata for each possible user code. Applications like zwavejs2mqtt and HomeAssistant operate mostly on values and need the metadata to discover the user codes.

Currently, this happens here https://github.com/zwave-js/node-zwave-js/blob/f5a353baa13334ea0c20f3ef3368710b9415e0e0/packages/zwave-js/src/lib/commandclass/UserCodeCC.ts#L274-L284, which is called when decoding `[Extended]UserCodeReports`.

We don't know for sure if the user codes are strings or Buffers, but I think it is safe to default to `string` before knowing what the user codes are like.

**Review by AlCalzone — CHANGES_REQUESTED** [review]

**Comment by AlCalzone** [comment]
Well, here's a test build for you to play with while I'm asleep:
@zwave-js-bot pack this

File: packages/zwave-js/src/lib/commandclass/UserCodeCC.ts (hunk 2 above)
Comment (sybohy) [reply packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]: hm interesting. i see what the problem is. Let me take a crack at writing a function that sets the metadata for each code even if we haven't queried the actual value from the device. I'm guessing this function will need to be used in a couple of spots (`persistUserCode` and `interview`).

File: packages/zwave-js/src/lib/commandclass/UserCodeCC.ts [hunk 3]
```diff
@@ -236,6 +236,48 @@ function validateCode(code: string, supportedChars: string): boolean {
 	return [...code].every((char) => supportedChars.includes(char));
 }
 
+function setUserCodeMetadata(this: UserCodeCC, userId: number) {
```
Comment (sybohy) [inline packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]: @AlCalzone I've moved the setting of the user code metadata to a separate function because it appears we need to call this functionality in a couple of different places. I've also gone ahead and **assumed** that the default type for a code is a string. Let me know if this is ok.

Actually quick question: do we want to be able to override the metadata type for the user code to Buffer in the event that it is in fact a buffer?

Comment (AlCalzone) [reply packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]: > Actually quick question: do we want to be able to override the metadata type for the user code to Buffer in the event that it is in fact a buffer?

Yeah, we need to be able to do that, when a device responds with a user code that needs to be represented as a buffer. I'd add an optional `userCode` parameter here and use that to distinguish. The current code will always set the metadata to string.

File: packages/zwave-js/src/lib/commandclass/UserCodeCC.ts [hunk 4]
```diff
@@ -236,6 +236,48 @@ function validateCode(code: string, supportedChars: string): boolean {
...
+			...ValueMetadata.Number,
+			label: `User ID status (${userId})`,
+			states: enumValuesToMetadataStates(
+				UserIDStatus,
+				supportedUserIDStatuses,
+			),
+		});
+	}
+	const codeMetadata: ValueMetadata = {
+		...ValueMetadata.String,
```
Comment (AlCalzone) [inline packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]: This needs to distinguish the type based on the actual user code (and default to string if none was passed)

File: packages/zwave-js/src/lib/commandclass/UserCodeCC.ts [hunk 5]
```diff
@@ -236,6 +236,48 @@ function validateCode(code: string, supportedChars: string): boolean {
...
+		minLength: 4,
+		maxLength: 10,
+		label: `User Code (${userId})`,
+	};
+	if (valueDB.getMetadata(codeValueId)?.type !== codeMetadata.type) {
+		valueDB.setMetadata(codeValueId, codeMetadata);
+	}
```
Comment (AlCalzone) [inline packages/zwave-js/src/lib/commandclass/UserCodeCC.ts:284]: Then this takes care of updating the metadata if necessary.

File: packages/zwave-js/src/lib/commandclass/UserCodeCC.ts [hunk 6]
```diff
@@ -271,29 +313,8 @@ function persistUserCode(
...
-				: ValueMetadata.Buffer),
-			minLength: 4,
-			maxLength: 10,
-			label: `User Code (${userId})`,
-		};
-		if (valueDB.getMetadata(codeValueId)?.type !== codeMetadata.type) {
-			valueDB.setMetadata(codeValueId, codeMetadata);
-		}
-
+		// Always create metadata in case it does not exist
```
Comment (AlCalzone) [inline packages/zwave-js/src/lib/commandclass/UserCodeCC.ts:305]: Can't comment on the correct line, but `const supportedUserIDStatuses` isn't used in this method any longer and can be removed.

File: packages/zwave-js/src/lib/driver/ZWaveOptions.ts [hunk 7]
```diff
@@ -59,8 +59,8 @@ export interface ZWaveOptions {
 	 */
 	skipInterview?: boolean;
 
-	/** Allows you to skip user code interview */
-	skipUserCodeInterview?: boolean;
+	/** Allows you to query all user code during the interview of the UserCode CC */
+	queryAllUserCodes?: boolean;
```
Comment (AlCalzone) [inline packages/zwave-js/src/lib/driver/ZWaveOptions.ts]:
```suggestion
	/**
	 * Whether all user code should be queried during the interview of the UserCode CC.
	 * Note that enabling this can cause a lot of traffic during the interview.
	 */
	queryAllUserCodes?: boolean; // default: false
```

Comment (AlCalzone) [reply packages/zwave-js/src/lib/driver/ZWaveOptions.ts]: Also, do we still want to merge the interview settings under a common property?

File: packages/zwave-js/src/lib/commandclass/UserCodeCC.ts [hunk 8]
```diff
@@ -755,8 +776,14 @@ export class UserCodeCC extends CommandClass {
 			return;
 		}
 
+		let nextUserId = 1;
+		while (nextUserId > 0 && nextUserId <= supportedUsers) {
+			setUserCodeMetadata.call(this, nextUserId);
+			nextUserId += 1;
+		}
```
Comment (AlCalzone) [inline packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]:
```suggestion
		for (let userId = 1; userId <= supportedUsers, userId++) {
			setUserCodeMetadata.call(this, userId);
		}
```

**Review by AlCalzone — CHANGES_REQUESTED** [review]

File: packages/zwave-js/src/lib/commandclass/UserCodeCC.ts (hunk 8 above)
Comment (sybohy) [reply packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]: i can't believe i wrote `nextUserId += 1` 🤦🤦🤦

**Comment by sybohy** [comment]
@zwave-js-bot fix lint

**Comment by AlCalzone** [comment]
Damn Github requiring me to approve your workflow runs. About time we get this merged so you're whitelisted.

File: packages/zwave-js/src/lib/driver/ZWaveOptions.ts [hunk 9]
```diff
@@ -53,12 +53,19 @@ export interface ZWaveOptions {
...
+		 * Set this to true to skip the controller interview. Useful for testing purposes
+		 */
+		skipInterview?: boolean;
 
+		/**
+		 * Whether all user code should be queried during the interview of the UserCode CC.
+		 * Note that enabling this can cause a lot of traffic during the interview.
+		 */
+		queryAllUserCodes?: boolean;
+	};
```
Comment (sybohy) [inline packages/zwave-js/src/lib/driver/ZWaveOptions.ts:68]: this needs to be added to `8.0.0` migration notes as a breaking change. Not sure if there's a process for this?

**Comment by sybohy** [comment]
@AlCalzone actually i'd love another build with these latest changes

File: packages/zwave-js/src/lib/driver/ZWaveOptions.ts (hunk 9 above)
Comment (AlCalzone) [reply packages/zwave-js/src/lib/driver/ZWaveOptions.ts:68]: Last time I added a migration guide in the docs and extended it in each PR.

**Comment by AlCalzone** [comment]
Doesn't seem to build - I think you forgot to update the default options.

**Comment by sybohy** [comment]
@AlCalzone are you ok with expanding the scope of this PR just a bit to get the build to go through? See this commit: https://github.com/zwave-js/node-zwave-js/pull/2932/commits/32b5f53220f7c9aa9ce3e93c39c129e7ed2342d2

File: packages/zwave-js/src/lib/driver/Driver.ts [hunk 10]
```diff
@@ -753,7 +756,7 @@ export class Driver extends TypedEventEmitter<DriverEventCallbacks> {
 			}
 		};
 
-		if (!this.options.skipInterview) {
+		if (!this.options.interview?.skipInterview) {
```
Comment (AlCalzone) [inline packages/zwave-js/src/lib/driver/Driver.ts:759]: The `?.` is unnecessary, but at least this should build now.

**Comment by AlCalzone** [comment]
Yup, definitely

**Comment by AlCalzone** [comment]
@zwave-js-bot pack this

File: packages/zwave-js/src/lib/commandclass/UserCodeCC.ts [hunk 11]
```diff
@@ -262,6 +261,38 @@ function persistUserCode(
...
+			states: enumValuesToMetadataStates(
+				UserIDStatus,
+				supportedUserIDStatuses,
+			),
+		});
+	}
+	const codeMetadata: ValueMetadata = {
+		...(typeof userCode === "object"
+			? ValueMetadata.Buffer
+			: ValueMetadata.String),
```
Comment (AlCalzone) [inline packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]:
```suggestion
		...(Buffer.isBuffer(userCode)
			? ValueMetadata.Buffer
			: ValueMetadata.String),
```
since I tend to stay away from `typeof userCode === "object"`

File: packages/zwave-js/src/lib/commandclass/UserCodeCC.ts [hunk 12]
```diff
@@ -755,8 +765,14 @@ export class UserCodeCC extends CommandClass {
 			return;
 		}
 
+		for (let userId = 1; userId <= supportedUsers; userId++) {
+			setUserCodeMetadata.call(this, userId);
+		}
+
 		// Synchronize user codes and settings
-		await this.refreshValues();
+		if (this.driver.options.interview?.queryAllUserCodes) {
```
Comment (AlCalzone) [inline packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]:
```suggestion
		if (this.driver.options.interview.queryAllUserCodes) {
```
After applying the default options, this is always defined.

Comment (AlCalzone) [reply packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]: Same goes for the other locations.

**Review by AlCalzone — CHANGES_REQUESTED** [review]
Just a few nits then I think this is ready if your tests work out.

File: packages/zwave-js/src/lib/commandclass/UserCodeCC.ts (hunk 12 above)
Comment (sybohy) [reply packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]: oh duh, i just realized you're doing a deep merge in the Driver constructor using the default options. Got it. Let me roll back these

Comment (sybohy) [reply packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]: fixed, via git commit --amend + force push

File: packages/zwave-js/src/lib/commandclass/UserCodeCC.ts (hunk 11 above)
Comment (sybohy) [reply packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]: i like this. 👍

File: packages/zwave-js/src/lib/driver/ZWaveOptions.ts (hunk 9 above)
Comment (sybohy) [reply packages/zwave-js/src/lib/driver/ZWaveOptions.ts:68]: If that's ok with you, I will add a `migrating-to-v8.md` file now that follows roughly the structure of prior file. I will then add this change in zwave options to it.

Comment (sybohy) [reply packages/zwave-js/src/lib/driver/ZWaveOptions.ts:68]: e.g. https://github.com/zwave-js/node-zwave-js/pull/2932/commits/fd4ad42b7a5fcb6ea4446920650c7668b6b6a92c

**Comment by sybohy** [comment]
@zwave-js-bot pack this

**Comment by sybohy** [comment]
@AlCalzone I've been testing this for the past 2 hours and it works like a charm on my end. Assuming there are no other issues, we can probably merge. Curious what the `v8.0.0` release process is like.

**Comment by AlCalzone** [comment]
@zwave-js-bot pack this

File: packages/zwave-js/src/lib/commandclass/UserCodeCC.ts (hunk 12 above)
Comment (AlCalzone) [reply packages/zwave-js/src/lib/commandclass/UserCodeCC.ts]: > git commit --amend + force push

You generally don't need to do that here - just makes following the changes in a PR harder. I squash merge every PR for a clean history.

**Comment by AlCalzone** [comment]
> Curious what the v8.0.0 release process is like.

I'm preparing the 8.x version in the `next` branch. I'm going to do a few more breaking changes, including the handling of endpoints as outlined in https://github.com/zwave-js/node-zwave-js/issues/2286 and changes to the build process.

From that branch I'm going to release a few alpha/beta prereleases for applications to test, then at some point make it official.

**Review by AlCalzone — APPROVED** [review]
I can't push changes to your branch - you probably disabled the "allow maintainer to make changes" checkbox. I'll just change the nits I have after merging.

**Comment by sybohy** [comment]
my apologies. I'll take a look at the settings in a minute
