### PR TITLE
fix: detect of serial disconnection, destroy driver on serial/socket failure

### LINKED ISSUE #2873: [bug] Detect serial disconnection
### Version

zwavejs2mqtt: 5.0.4.ebfd0b3
zwave-js: 7.7.5
home id: 4266870589
home hex: 0xfe53473d

**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

Build/Run method

- [ ] Docker
- [ ] PKG
- [ ] Snap package
- [x] Manually built (git clone - yarn install - yarn run build )

zwavejs2mqtt version: 5.0.4.ebfd0b3
zwave-js version: 7.7.5

### Describe the bug

the health is still OK event when the adapter is disconnected (not in the /dev/ttyACM... )

### To Reproduce

1. Check the health without service

```
curl localhost:8091/health -H "Accept: text/plain" -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* connect to 127.0.0.1 port 8091 failed: Connection refused
* Failed to connect to localhost port 8091: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8091: Connection refused
```
OK

2. Start service without adapter connected
```
yarn start
``` 

OK 

3. Check the health
```
curl localhost:8091/health -H "Accept: text/plain"
Error
```

OK

4. Connect the adapter wait a minute and check health

```
curl localhost:8091/health -H "Accept: text/plain"
Ok
```

OK

5. Remove the adapter wait x minutes and check health

```
curl localhost:8091/health -H "Accept: text/plain"
Ok
```

NOK

### Expected behavior

After removing adapter the health should be Error 

### Additional context

I'm trying to add to my app some info about problem with zWave adapter connection. 
In zigbee2mqtt it can be easy done via mqtt -> ``state_topic: "zigbee2mqtt/bridge/state"``

image

Is there any way (via mqtt or http) to have the real status about zwave?

 :pray:  Thanks 

BTW
this is the greatest web app I ever saw :+1:

### PR DESCRIPTION
**Pull request by robertsLando**
Fixes #2873

### CODE REVIEW

File: packages/serial/src/ZWaveSocket.ts [hunk 1]
```diff
@@ -17,8 +21,8 @@ export class ZWaveSocket extends ZWaveSerialPortBase {
 				create: () => new net.Socket(),
 				open: (serial: net.Socket) =>
 					new Promise((resolve) => {
-						serial.on("close", () => {
-							if (this.isOpen) {
+						serial.on("close", (err: DisconnectError) => {
+							if (err?.disconnected === true) {
```
Comment (AlCalzone) [inline packages/serial/src/ZWaveSocket.ts:25]: Are you sure about this? The type declarations claim that the parameter for the close event is a boolean. And the serialport code throws an error, so I would expect this to come through the `"error"` event.

File: packages/serial/src/ZWaveSocket.ts [hunk 2]
```diff
@@ -6,6 +6,10 @@ export type ZWaveSocketOptions =
 	| Omit<net.TcpSocketConnectOpts, "onread">
 	| Omit<net.IpcSocketConnectOpts, "onread">;
 
+export interface DisconnectError extends Error {
```
Comment (AlCalzone) [inline packages/serial/src/ZWaveSocket.ts]:
```suggestion
interface DisconnectError extends Error {
```
No need to export.

**Review by AlCalzone — CHANGES_REQUESTED** [review]

File: packages/serial/src/ZWaveSocket.ts (hunk 1 above)
Comment (AlCalzone) [reply packages/serial/src/ZWaveSocket.ts:25]: Ok, seems like the type declarations are incorrect:
https://serialport.io/docs/api-stream#close

File: packages/serial/src/ZWaveSocket.ts [hunk 3]
```diff
@@ -6,6 +6,10 @@ export type ZWaveSocketOptions =
...
+	disconnected: boolean;
+}
+
 /** A version of the Z-Wave serial binding that works using a socket (TCP or IPC) */
 export class ZWaveSocket extends ZWaveSerialPortBase {
```
Comment (AlCalzone) [inline packages/serial/src/ZWaveSocket.ts]: That's the wrong file! This is the
> serial binding that works using a socket (TCP or IPC)

You wanted to edit `ZWaveSerialPort.ts`, which uses the serialport binding.

Comment (robertsLando) [reply packages/serial/src/ZWaveSocket.ts]: I think it could be applied in both but ok I will move it to the other file

File: packages/serial/src/ZWaveSocket.ts [hunk 4]
```diff
@@ -18,7 +18,7 @@ export class ZWaveSocket extends ZWaveSerialPortBase {
 				open: (serial: net.Socket) =>
 					new Promise((resolve) => {
 						serial.on("close", () => {
-							if (this.isOpen) {
+							if (!this.isOpen) {
```
Comment (AlCalzone) [inline packages/serial/src/ZWaveSocket.ts]: Uhm, why? If the socket **is** open and suddenly out of nowhere the `"close"` event is emitted - that's unexpected IMO.

File: packages/serial/src/ZWaveSerialPort.ts [hunk 5]
```diff
@@ -27,6 +31,18 @@ export class ZWaveSerialPort extends ZWaveSerialPortBase {
 					}),
 				open: (serial: SerialPort) =>
 					new Promise((resolve) => {
+						// detect serial disconnection errors
+						serial.on("close", (err?: DisconnectError) => {
+							if (err?.disconnected === true) {
+								this.emit(
```
Comment (AlCalzone) [inline packages/serial/src/ZWaveSerialPort.ts:37]: Did you test this? Does it work?

**Review by AlCalzone — CHANGES_REQUESTED** [review]

File: packages/serial/src/ZWaveSocket.ts (hunk 4 above)
Comment (robertsLando) [reply packages/serial/src/ZWaveSocket.ts]: Revert error, sorry

File: packages/serial/src/ZWaveSerialPort.ts (hunk 5 above)
Comment (robertsLando) [reply packages/serial/src/ZWaveSerialPort.ts:37]: Not tested yet

**Comment by AlCalzone** [comment]
Works like a charm. I've changed it so the driver destroys itself when the socket or serial port fails during usage. Previously it only destroyed itself when it failed during opening.

**Review by AlCalzone — APPROVED** [review]
