### PR TITLE
fix: update import script to handle new OpenHAB database

### LINKED ISSUE #1226: Updating devices from source 'oh' does not work due to URL changes
**Describe the bug**
The OpenHAB source for Z-Wave devices from <https://www.cd-jackson.com/index.php/zwave/zwave-device-database/> has changed to <https://opensmarthouse.org/zwavedatabase/> causing the device update task to fail.

**To Reproduce**
1. `yarn run config -D -s oh`

**Logfile:**
```bash
$ yarn run config -D -s oh
yarn run v1.22.10
$ ts-node maintenance/importConfig.ts -D -s oh
Fetching manufacturers...
./node_modules/axios/lib/core/createError.js:16
  var error = new Error(message);
              ^
Error: Request failed with status code 404
    at createError (./node_modules/axios/lib/core/createError.js:16:15)
    at settle (./node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (./node_modules/axios/lib/adapters/http.js:244:11)
    at IncomingMessage.emit (node:events:388:22)
    at IncomingMessage.EventEmitter.emit (node:domain:470:12)
    at endReadableNT (node:internal/streams/readable:1295:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Solution Infos**
This URL returns a list of devices in JSON format:
<https://opensmarthouse.org/dmxConnect/api/zwavedatabase/device/list.php?filter=&manufacturer=-1&limit=2000>

This URL returns the details of a device in JSON format:
<https://opensmarthouse.org/dmxConnect/api/zwavedatabase/device/read.php?device_id=256>

More URLs can be observed using the network tab of the browser developer tools.
NOTE: This website aggressively caches requests in the LocalStorage, so reloading a page may not trigger any requests. Clearing the LocalStorage of the site opensparthouse.org solves this.

### PR DESCRIPTION
**Pull request by AlCalzone**
fixes: #1226 

/cc @ahochsteger

### CODE REVIEW

File: maintenance/importConfig.ts [hunk 1]
```diff
@@ -915,14 +836,15 @@ async function parseOHConfigFile(
 	assertValid(json);
 
 	const ret: Record<string, any> = {
-		_approved: json.state === "1" || json.state === 1,
+		_approved: json.approved === "1" || json.approved === 1,
```
Comment (robertsLando) [inline maintenance/importConfig.ts]: This can be removed

File: maintenance/importConfig.ts [hunk 2]
```diff
@@ -915,14 +836,15 @@ async function parseOHConfigFile(
...
 		...(json.errors?.length ? { _errors: json.errors } : undefined),
 		...(json.warnings?.length ? { _warnings: json.warnings } : undefined),
-		manufacturer: json.manufacturer,
-		manufacturerId: findManufacturerId(content, json),
+		manufacturer: json.manufacturer.label,
+		manufacturerId: formatId(json.manufacturer.reference),
 		label: sanitizeText(json.label),
 		description: sanitizeText(json.description),
-		devices: json.type_id
+		devices: json.device_ref
```
Comment (robertsLando) [inline maintenance/importConfig.ts:845]: Shouldn't this extend existing config? Does this overrides the config file?

**Review by robertsLando — CHANGES_REQUESTED** [review]

File: maintenance/importConfig.ts (hunk 2 above)
Comment (AlCalzone) [reply maintenance/importConfig.ts:845]: Yep, the OH import overwrites the original files. If someone wants to implement merging them, go ahead. I don't bother with that right now.
