### PR TITLE
fix: recreate transports, reconfigure loggers when updating log config

### LINKED ISSUE #1908: Driver.updateLogConfig changes the LogConfig but that doesn't actually change the logging
**Checklist:**

- [x] I am **not** using HomeAssistant. **Or:** a developer has told me to come here.
- [x] I am **not** using ZWaveJS2MQTT. **Or:** a developer has told me to come here.
- [x] I have checked the troubleshooting section and my problem is **not** described there.
- [x] I have read the changelog problem was **not** mentioned there.

**Describe the bug**

I have attempted to update the log config to set the level to `debug` via a Home Assistant websocket command. When I get the log config, it shows that the change is applied, but I don't see debug statements in the Z-Wave JS server addon logs when the change is applied.

The context of the request to re-add this feature and to report this is that we want to add functionality to the HA UI that will make it easier for us (and you) to get logs from users

**Device information**

Which device(s) is/are affected (make/model)?  N/A
What are the node IDs? N/A

**Did you change anything?**
- [ ] **Yes**: *(please describe)*
- [x] **No**

**Did this use to work before?**
- [ ] **Don't know**, this is a new device
- [x] **No**, it never worked anywhere
- [ ] **Yes**, in: *(specify application with versions)*
    
**How are you using `node-zwave-js`**
- [ ] `zwavejs2mqtt` (latest) docker image
- [ ] `zwavejs2mqtt` (dev) docker image
- [ ] `zwavejs2mqtt` Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] ioBroker.zwave2 adapter
- [x] `HomeAssistant` version 2021.3.0b2 (using Z-Wave JS server 0.1.10 which has zwave-js-server 1.1.0 embedded
- [ ] Pkg
- [ ] Manual Docker build
    - `node-zwave-js` branch: 
    - `zwavejs2mqtt` branch: 
- [ ] Manually built (as described in the [docs](https://zwave-js.github.io/node-zwave-js/#/development/installing-from-github)) 
- [ ] Other: 

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Additional context**

**Logfile:**

```console
$0.hass.callWS({type: "zwave_js/update_log_config", entry_id: "blah", config: {level: "debug"}}).then(response =>
  console.log("response: ", response));
Promise {<pending>}
VM2316:2 response:  null
$0.hass.callWS({type: "zwave_js/get_log_config", entry_id: "blah"}).then(response =>
  console.log("response: ", response));
Promise {<pending>}
VM2322:2 response:  {enabled: true, level: 5, log_to_file: false, filename: "/usr/lib/node_modules/@zwave-js/server/dist/bin/zwave-248.log", force_console: true}
```

### PR DESCRIPTION
**Pull request by AlCalzone**
fixes: #1908

### CODE REVIEW

File: packages/core/src/log/shared.ts [hunk 1]
```diff
@@ -137,19 +141,40 @@ export class ZWaveLogContainer extends winston.Container {
 	}
 
 	public updateConfiguration(config: DeepPartial<LogConfig>): void {
+		const changedLoggingTarget =
+			config.logToFile != undefined &&
+			config.logToFile !== this.logConfig.logToFile;
+
+		const changedLogLevel =
+			config.level != undefined && config.level !== this.logConfig.level;
```
Comment (robertsLando) [inline packages/core/src/log/shared.ts:152]: Is the  `!=` used on purpose instead of `!==` to catch also `null`?

File: packages/core/src/log/shared.ts [hunk 2]
```diff
@@ -137,19 +141,40 @@ export class ZWaveLogContainer extends winston.Container {
...
+
+		const changedFilename =
+			config.filename != undefined &&
```
Comment (robertsLando) [inline packages/core/src/log/shared.ts:155]: Same?

File: packages/core/src/log/shared.ts (hunk 1 above)
Comment (AlCalzone) [reply packages/core/src/log/shared.ts:152]: Yep, I always do that.

File: packages/core/src/log/shared.ts (hunk 2 above)
Comment (AlCalzone) [reply packages/core/src/log/shared.ts:155]: Dito

**Comment by robertsLando** [comment]
The reason to use string loglevels ? More user friendly? BTW I would keep the fallback to numeric to don't introduce breaking changes

**Comment by AlCalzone** [comment]
Winston transports only accept string log levels and I find it extremely awkward to look up what the numeric log level is if I want to set it to "debug". Especially if zwave-js has to reverse the lookup do do anything with the log level.

**Review by robertsLando — DISMISSED** [review]

**Comment by AlCalzone** [comment]
@robertsLando does this break your code?

**Comment by robertsLando** [comment]
> @robertsLando does this break your code?

Sorry @AlCalzone I may have missed this! BTW everything seems ok

**Comment by AlCalzone** [comment]
Its marked as breaking anyways, so you'll have time to test out v7
